### ISSUE TITLE
[Bug]: Extension is not working after update

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [CoderLine/mocha-vscode#165]
### Checklist

- [X] I have read and agree to the [Code of Conduct](https://github.com/CoderLine/mocha-vscode/blob/main/code-of-conduct.md)
- [X] I have searched for [related issues](https://github.com/CoderLine/mocha-vscode/issues) and [discussions](https://github.com/CoderLine/mocha-vscode/discussions) but they did not match this problem.
- [ ] I want to contribute a bugfix myself.

### Actual behavior

Extension can't be started.

### Expected behavior

Extension must be started and show tests

### Minimal, Reproducible Example

https://github.com/muhammadyusuf-kurbonov/mocha-forVSCode-bug-example

### Output

Extension Host output:
```
2024-10-14 11:39:33.091 [error] Error: Command failed: npm install --no-save --omit=dev --omit=optional --omit=peer --prefer-offline --no-audit --progress=false @esbuild/linux-x64@0.24.0
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: mocha-vscode@1.2.1
npm error Found: eslint@undefined
npm error node_modules/eslint
npm error   dev eslint@"^9.11.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^8.57.0 || ^9.0.0" from @typescript-eslint/parser@8.7.0
npm error node_modules/@typescript-eslint/parser
npm error   dev @typescript-eslint/parser@"^8.6.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/muhammadyusuf-kurbonov/.npm/_logs/2024-10-14T06_39_30_751Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/muhammadyusuf-kurbonov/.npm/_logs/2024-10-14T06_39_30_751Z-debug-0.log

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:423:12)
	at ChildProcess.emit (node:events:519:28)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:339:12)
```

### Plugin Version Details

Name: Mocha for VS Code
Id: coderline.mocha-vscode
Description: Run and debug Mocha tests right within VS Code.
Version: 1.2.1
Publisher: CoderLine
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=coderline.mocha-vscode

### VS Code Version Details

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.12-200.fc40.x86_64

**Comment by muhammadyusuf-kurbonov** [comment]
```
2024-10-16 11:39:59.566 [error] Error: ENOENT: no such file or directory, rename '/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/tmp/package' -> '/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/node_modules/@esbuild/linux-x64'
	at async Object.rename (node:internal/fs/promises:784:10)
	at async vKe (/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/out/extension.js:587:54595)
	at async /home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/out/extension.js:614:18395
```
